name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
      env-file:
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest


    env:
      STAGE: ${{ inputs.stage }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: "recursive"
      - run: |
          cat dags/veda_data_pipeline/veda_pipeline_tasks/README
          echo $STAGE
